### ISSUE TITLE
Error while generate code

### ISSUE THREAD

**Issue by p3le** [amazon-php/sp-api-sdk#682]
When I try to run generate.sh from bin directory, I keep getting errors: 

`[main] ERROR o.o.c.config.CodegenConfigurator - /sp-api/config/generator-aplus.yaml (No such file or directory)
[main] ERROR o.o.c.config.CodegenConfigurator - /sp-api/config/generator-aplus.yaml (No such file or directory)
Exception in thread "main" java.lang.RuntimeException: Unable to deserialize config file: /sp-api/config/generator-aplus.yaml
        at org.openapitools.codegen.config.CodegenConfigurator.readDynamicSettings(CodegenConfigurator.java:195)
        at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:96)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:356)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)`
        
 How to fix this? 
 
 Ubuntu 24.04, Docker version 27.3.1, build ce12230

**Comment by jasonhebert** [comment]
Try running `composer generate` from the main directory
